build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.18"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn-control-plane-6nodes
  cron: '@yearly'
  steps:
    cluster_profile: aws-perfscale-qe
    env:
      ADDITIONAL_WORKER_NODES: "3"
      BASE_DOMAIN: qe.devcluster.openshift.com
      ENABLE_LOCAL_INDEX: "true"
      ES_TYPE: qe
      EXTRA_FLAGS: --churn-duration=20m --pod-ready-threshold=20s
      IGNORE_JOB_ITERATIONS: "true"
      ITERATION_MULTIPLIER_ENV: "15"
      OUTPUT_FORMAT: JUNIT
      RUN_ORION: "true"
      TEST_SUITE: ""
      TEST_TYPE: upgrade-conformance
      TEST_UPGRADE_OPTIONS: ""
      VERSION: "4.19"
      ZONES_COUNT: "3"
    test:
    - ref: openshift-qe-workers-scale
    - ref: openshift-e2e-test
    - chain: openshift-qe-control-plane
    - chain: openshift-qe-orion-consolidated
    workflow: openshift-qe-installer-aws
  timeout: 6h30m0s
zz_generated_metadata:
  branch: main
  org: openshift-eng
  repo: ocp-qe-perfscale-ci
  variant: 4.19-upgrade-from-stable-4.18
