build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
images:
- dockerfile_path: prow/Dockerfile
  to: ocp-qe-perfscale-ci-aws-414-ovnic
promotion:
  namespace: ci
  tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: ocp-qe-perfscale-aws-ci-tests-large-scale-ovnic
  cron: 0 12 * * 1
  steps:
    cluster_profile: aws-perfscale
    env:
      BASE_DOMAIN: perfscale.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "252"
      COMPUTE_NODE_TYPE: m5.2xlarge
      ITERATION_MULTIPLIER_ENV: "6"
      SIZE_VARIANT: xlarge
    post:
    - chain: ipi-aws-post
    pre:
    - chain: ipi-aws-pre
    - chain: create-infra-move-ingress-monitoring-registry
    workflow: openshift-qe-control-plane
  timeout: 8h0m0s
- as: ocp-qe-perfscale-aws-cni-tests-large-scale-ovnic
  cron: 0 12 * * 1
  steps:
    cluster_profile: aws-perfscale
    env:
      BASE_DOMAIN: perfscale.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "252"
      COMPUTE_NODE_TYPE: m5.2xlarge
      PODS_PER_NODE: "120"
      SIZE_VARIANT: xlarge
    post:
    - chain: ipi-aws-post
    pre:
    - chain: ipi-aws-pre
    - chain: create-infra-move-ingress-monitoring-registry
    workflow: openshift-qe-node-density-cni
  timeout: 8h0m0s
- as: ocp-qe-perfscale-aws-cnihighppn-tests-large-scale-ovnic
  cron: 0 12 * * 1
  steps:
    cluster_profile: aws-perfscale
    env:
      BASE_DOMAIN: perfscale.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "252"
      COMPUTE_NODE_TYPE: m5.2xlarge
      PODS_PER_NODE: "220"
      SIZE_VARIANT: xlarge
    post:
    - chain: ipi-aws-post
    pre:
    - chain: ipi-aws-pre
    - chain: create-infra-move-ingress-monitoring-registry
    workflow: openshift-qe-node-density-cni
  timeout: 8h0m0s
zz_generated_metadata:
  branch: main
  org: openshift-qe
  repo: ocp-qe-perfscale-ci
  variant: aws-4.14-ovnic
